### ISSUE TITLE
Some Hebrew letters with the wrong tag

### ISSUE THREAD

**Issue by LAfricain** [BibleCorps/ENG-B-AKJV2018-pd-PSFM#6]
In the Psalm usfm file, some of the hebrew  letters are preceded by the wrong  usfm tag (by a number), example:
`129 PE. 161 SCHIN. 169 TAU`

**Comment by cmahte** [comment]
\rem Version statements in all files did not have preceding slash mark. 

Psalms 129, 161, 169 \qa tags missing and extra verse number. 

Fixed.
